export { root } from './root'
export { news } from './news'
export { teams } from './teams'
export { form } from './form'
export { admin } from './admin'
export { auth } from './auth'
export { create } from './create'
